# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 342)
        MainWindow.setMinimumSize(QtCore.QSize(523, 342))
        MainWindow.setMaximumSize(QtCore.QSize(523, 342))
        MainWindow.setStyleSheet("QProgressBar {\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    background-color: rgb(142, 68, 173);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 12px;\n"
"\n"
"    margin: 0.5px;\n"
"    background-color: rgb(44, 62, 80);\n"
"}\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    color: rgb(142, 68, 173);\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.04, x2:0.985782, y2:0.693182, stop:0 rgba(44, 62, 80, 255), stop:1 rgba(38, 53, 69, 255));\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_all = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_all.setFont(font)
        self.frame_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_all.setObjectName("frame_all")
        self.prog = QtWidgets.QProgressBar(self.frame_all)
        self.prog.setGeometry(QtCore.QRect(100, 232, 331, 31))
        self.prog.setProperty("value", 24)
        self.prog.setObjectName("prog")
        self.label = QtWidgets.QLabel(self.frame_all)
        self.label.setGeometry(QtCore.QRect(70, 60, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("    background-color: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_tz = QtWidgets.QLabel(self.frame_all)
        self.label_tz.setGeometry(QtCore.QRect(160, 290, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(11)
        self.label_tz.setFont(font)
        self.label_tz.setStyleSheet("    background-color: transparent;")
        self.label_tz.setTextFormat(QtCore.Qt.RichText)
        self.label_tz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tz.setObjectName("label_tz")
        self.label_2 = QtWidgets.QLabel(self.frame_all)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:  transparent ;\n"
"color: rgb(90, 43, 110);")
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.frame_all, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "This is The start Of my App"))
        self.label_tz.setText(_translate("MainWindow", "<strong>Created</strong> By 0xtz"))
        self.label_2.setText(_translate("MainWindow", "My App Description"))
